#FROM node:latest # v9.5
FROM node:6.13.0

# 
RUN mkdir -p /app-data/my-app
WORKDIR /app-data/my-app

# 앱 소스 추가
ADD ./my-app /app-data/my-app
ADD ~/GraceChurch-Home-b11a25cab0ba.json /app-data

# Google Speech API
ENV GOOGLE_APPLICATION_CREDENTIALS /app-data/GraceChurch-Home-b11a25cab0ba.json

# 앱 의존성 설치
RUN npm install


EXPOSE 3000
CMD [ "npm", "start" ]
